# Generated by Django 5.2.4 on 2026-05-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_chain', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
